### ISSUE TITLE
Elaboration on diff_tads

### ISSUE THREAD

**Issue by The-Hungry-Caterpillar** [dozmorovlab/UO_project_2021#22]
need to elaborate about ICE method and finding cutoff values in [this readme](https://github.com/dozmorovlab/UO_project_2021/blob/main/05_differential_tads/README.md). 

also need to update the output structure (perhaps using tree?) and should pass an option for p-value cutoff in TAD comparison

**Comment by mdozmorov** [comment]
The original paper Imakaev, Maxim, Geoffrey Fudenberg, Rachel Patton McCord, Natalia Naumova, Anton Goloborodko, Bryan R. Lajoie, Job Dekker, and Leonid A. Mirny. “Iterative Correction of Hi-C Data Reveals Hallmarks of Chromosome Organization.” Nature Methods 9, no. 10 (October 2012): 999–1003. https://doi.org/10.1038/nmeth.2148.
