### ISSUE TITLE
merge readme

### ISSUE THREAD

**Issue by The-Hungry-Caterpillar** [dozmorovlab/UO_project_2021#23]
[mergereadme](https://github.com/dozmorovlab/UO_project_2021/blob/main/03_merge_replicates/README.md) needs work.

needs desc, input, and output

**Comment by bgpalmer** [comment]
I don't think the script is right. There isn't a split function anywhere

**Comment by The-Hungry-Caterpillar** [comment]
Okay I'll take a look. I have the script still.
