### ISSUE TITLE
post-merge analysis

### ISSUE THREAD

**Issue by The-Hungry-Caterpillar** [dozmorovlab/UO_project_2021#24]
it might be better to roll [post merge analysis](https://github.com/dozmorovlab/UO_project_2021/tree/main/04_post_merge_analysis) into [visualize replicates](https://github.com/dozmorovlab/UO_project_2021/tree/main/02_visualize_replicates) since they both use similar input and output formats

**Comment by bgpalmer** [comment]
It will break the sequence paradigm we have currently with the folders in the parent directory, but this is also a valid point

**Comment by The-Hungry-Caterpillar** [comment]
Okay let's leave it how it is then
